### PR TITLE
LPS-70229 Testing the handler with an integration test

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@ambrinchaudhary recuerda que necesitas estos cambios en portal para que todo funcione correctamente: https://github.com/csierra/liferay-portal/pull/260.

**Comment by 4lejandrito** [comment]
\cc @sergiogonzalez

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/4lejandrito/com-liferay-adaptive-media/pull/5. [See changes here.](https://github.com/ambrinchaudhary/com-liferay-adaptive-media/compare/ea84532~3...ea84532) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
